services:
  postgres:
    image: cloudticket-postgres-image-v2:latest
    container_name: cloudticket-postgres-v2

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


    volumes:
      - cloudticket-postgres-volume-v2:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend

    image: cloudticket-backend-image-v2:latest
    container_name: cloudticket-backend-v2

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

    depends_on:
      - postgres

volumes:
  cloudticket-postgres-volume-v2:
