services:
  postgres:
    image: cloudticket-postgres-image-v2:latest
    container_name: cloudticket-postgres-v2

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


    volumes:
      - cloudticket-postgres-volume-v2:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend

    image: cloudticket-backend-image-v2:latest
    container_name: cloudticket-backend-v2

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SQS_QUEUE_NAME: ${SQS_QUEUE_NAME}

    depends_on:
      - postgres

  localstack:
    image: localstack/localstack:latest
    container_name: cloudticket-localstack-v2

    ports:
      - "4566:4566"

    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: ap-southeast-2
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  cloudticket-postgres-volume-v2:
